[global]
db_path = "/data/zec-wallet-test.db"
confirmations = 6
lwd_url = "https://zec.rocks:443"
notify_tx_url = "http://btcpayserver:9000/zcashlikedaemoncallback/tx?cryptoCode=zec&hash="
poll_interval = 60

[debug]
address = "127.0.0.1"

[release]
address = "0.0.0.0"
